---
# tasks file for vpc

# Check first if credentials are set
- assert:
    that:
       - aws_access_key != none
       - aws_secret_key != none
    fail_msg: You have to specify your credentials in /inventories/<stage>/group_vars/all/credentials.yml   

- import_tasks: create_vpc.yml