---
# tasks file for ec2

# Check first if credentials are set
- assert:
    that:
       - aws_access_key != none
       - aws_secret_key != none
    fail_msg: You have to specify your credentials in /inventories/<stage>/group_vars/all/credentials.yml   

- import_tasks: security_group.yml
- import_tasks: spinup-ec2-instance.yml
